name: CI & CD
# NOTE: CI -> Continuous Integration
# NOTE: CD -> Continuous Delivery

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            reason:
                description: Reason of re-running this workflow
                required: false
                type: string

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

env:
    CI: true

permissions:
    contents: read
    pull-requests: read

jobs:
    lint_typos:
        name: Lint
        uses: shan-shan-dev/.github/.github/workflows/typos.yml@main
